[
	{
		"shape": [
			["LINE_MODE",     0, 1,  -1.5f,   1],
			["CURVE_MODE",    0, 1,   .75f,   1,  1.5f,.5f,  1.5f, 0,  8],
			["CURVE_MODE", 1.5f, 0,   1.5f,-.5f,  .75f, -1,     0,-1,  8],
			["LINE_MODE",     0,-1,  -1.5f,  -1],
			["CURVE_MODE",-1.5f, 1,    -1f,   1,  -.5f,.5f,  -.5f, 0,  8],
			["CURVE_MODE", -.5f, 0,   -.5f,-.5f,   -1f, -1,  -1.5,-1,  8]
		],
		"filled": false
	}
]